language: android
jdk: oraclejdk8
android:
  components:
    # SDK Tools
    - platform-tools
    - tools

    # Build Tools
    - build-tools-23.0.2

    # SDK Version
    - android-23

    # Additional Components
    - extra-android-support
    - extra-android-m2repository

script: 
  - chmod +x gradlew
  - ./gradlew assembleDebug
  
deploy:
  provider: releases
  api_key: 9fd4023bd5b0b26dd78c0524eae775cef730e14a
  file: app/build/outputs/apk/app-debug.apk
  skip_cleanup: true
  on:
    tags: true
